title: Paulo Czarnewski
baseurl: /czarnewski

relative_links:
  enabled: true
  collections: true

include:
  - index.md

markdown: CommonMark
commonmark:
  options: ["SMART", "FOOTNOTES", "UNSAFE"]
  extensions: ["strikethrough", "autolink", "table"]
