title: Paulo Czarnewski
baseurl: /czarnewski

relative_links:
  enabled: true
  collections: true

include:
  - index.md

theme: jekyll-theme-minimal
plugins:
 - jekyll-relative-links
 
markdown: CommonMarkGhPages
commonmark:
  options: ["SMART", "FOOTNOTES", "UNSAFE"]
  extensions: ["strikethrough", "autolink", "table"]
