title: Paulo Czarnewski
description: KTH | SU
theme: jekyll-theme-minimal
plugins:
  - jekyll-relative-links
markdown: CommonMarkGhPages
relative_links:
  enabled: true
  collections: true
include:
  - index.md
